package com.kitsune.core.memory.lore

import com.kitsune.core.data.local.entities.ChatEntity
import com.kitsune.core.data.local.entities.ChatMode
import com.kitsune.core.data.local.entities.LoreEntryEntity
import com.kitsune.core.data.local.entities.LoreEntryType
import com.kitsune.core.data.local.entities.MemoryFragmentSource
import com.kitsune.core.data.local.entities.MessageEntity
import com.kitsune.core.data.local.entities.MessageRole
import com.kitsune.core.data.repository.ChatRepository
import com.kitsune.core.data.repository.LoreEntryRepository
import com.kitsune.core.memory.semantic.IndexMemoryFragmentUseCase
import com.kitsune.core.network.preferences.LlmModelResolver
import com.kitsune.core.network.repository.ChatCompletionRepository
import com.kitsune.core.network.repository.ChatCompletionResult
import com.kitsune.core.network.repository.ChatTurn
import io.mockk.coEvery
import io.mockk.coJustRun
import io.mockk.coVerify
import io.mockk.mockk
import io.mockk.slot
import kotlinx.coroutines.test.runTest
import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Test

private const val CHAT_ID = "chat-1"

private fun message(index: Int, content: String = "message $index") = MessageEntity(
    id = "msg-$index",
    chatId = CHAT_ID,
    role = if (index % 2 == 0) MessageRole.USER else MessageRole.ASSISTANT,
    content = content,
    imageAttachmentPath = null,
    tokenCount = null,
    createdAt = index.toLong()
)

private fun chatEntity(storyTimeAnchor: String = "") = ChatEntity(
    id = CHAT_ID,
    universeId = null,
    personaId = "persona-1",
    title = "Test chat",
    mode = ChatMode.CHAT,
    storyTimeAnchor = storyTimeAnchor,
    createdAt = 0L,
    updatedAt = 0L
)

class ExtractLoreEntriesUseCaseTest {

    private val loreEntryRepository = mockk<LoreEntryRepository>()
    private val chatRepository = mockk<ChatRepository> {
        coEvery { getById(CHAT_ID) } returns chatEntity()
    }
    private val chatCompletionRepository = mockk<ChatCompletionRepository>()
    private val llmModelResolver = mockk<LlmModelResolver> {
        coEvery { resolve(any()) } returns "gpt-4.1"
    }
    private val indexMemoryFragmentUseCase = mockk<IndexMemoryFragmentUseCase>()

    private val useCase = ExtractLoreEntriesUseCase(
        loreEntryRepository,
        chatRepository,
        chatCompletionRepository,
        llmModelResolver,
        indexMemoryFragmentUseCase
    )

    private fun completion(content: String) =
        Result.success(ChatCompletionResult(content = content, usage = null, modelUsed = "gpt-5-mini"))

    @Test
    fun `does nothing when there are no messages`() = runTest {
        useCase(CHAT_ID, emptyList())

        coVerify(exactly = 0) { loreEntryRepository.getByChat(any()) }
        coVerify(exactly = 0) { chatCompletionRepository.complete(any(), any(), any(), any(), any(), any(), any(), any(), any()) }
    }

    @Test
    fun `creates a new lore entry from the AI response and indexes it`() = runTest {
        coEvery { loreEntryRepository.getByChat(CHAT_ID) } returns emptyList()
        coEvery { loreEntryRepository.findByChatAndNameOrAlias(CHAT_ID, any()) } returns null
        coEvery { chatCompletionRepository.complete(any(), any(), any(), any(), any(), any(), any(), any(), any()) } returns completion(
            """{"entries": [{"name": "Aria", "entryType": "CHARACTER", "summary": "A mercenary.", "content": "Tall, silver hair, cold but loyal."}]}"""
        )
        coEvery { loreEntryRepository.upsert(any()) } returns Unit
        coJustRun { indexMemoryFragmentUseCase(any(), any(), any(), any()) }

        useCase(CHAT_ID, listOf(message(1)))

        coVerify {
            loreEntryRepository.upsert(
                withArg { entry ->
                    assertEquals("Aria", entry.name)
                    assertEquals(LoreEntryType.CHARACTER, entry.entryType)
                    assertEquals("A mercenary.", entry.summary)
                    assertTrue(entry.isAutoGenerated)
                    assertEquals(1, entry.version)
                    assertEquals(CHAT_ID, entry.chatId)
                }
            )
        }
        coVerify { indexMemoryFragmentUseCase(CHAT_ID, MemoryFragmentSource.LORE_ENTRY, any(), any()) }
    }

    @Test
    fun `sets occurredAt on a newly created EVENT entry`() = runTest {
        coEvery { loreEntryRepository.getByChat(CHAT_ID) } returns emptyList()
        coEvery { loreEntryRepository.findByChatAndNameOrAlias(CHAT_ID, any()) } returns null
        coEvery { chatCompletionRepository.complete(any(), any(), any(), any(), any(), any(), any(), any(), any()) } returns completion(
            """{"entries": [{"name": "The docks confrontation", "entryType": "EVENT", "summary": "A tense standoff.", "content": "Details.", "occurredAt": "Early winter, three days before the wedding."}]}"""
        )
        coEvery { loreEntryRepository.upsert(any()) } returns Unit
        coJustRun { indexMemoryFragmentUseCase(any(), any(), any(), any()) }

        useCase(CHAT_ID, listOf(message(1)))

        coVerify {
            loreEntryRepository.upsert(
                withArg { entry ->
                    assertEquals(LoreEntryType.EVENT, entry.entryType)
                    assertEquals("Early winter, three days before the wedding.", entry.occurredAt)
                }
            )
        }
    }

    @Test
    fun `never overwrites occurredAt on an existing entry re-matched by a later batch`() = runTest {
        val existing = LoreEntryEntity(
            id = "event-1",
            chatId = CHAT_ID,
            entryType = LoreEntryType.EVENT,
            name = "The docks confrontation",
            summary = "old summary",
            content = "old content",
            isAutoGenerated = true,
            occurredAt = "Early winter, three days before the wedding.",
            version = 1,
            createdAt = 10L,
            updatedAt = 10L
        )
        coEvery { loreEntryRepository.getByChat(CHAT_ID) } returns listOf(existing)
        coEvery { chatCompletionRepository.complete(any(), any(), any(), any(), any(), any(), any(), any(), any()) } returns completion(
            """{"entries": [{"name": "The docks confrontation", "entryType": "EVENT", "summary": "Enriched summary.", "content": "More detail.", "occurredAt": "A completely different, later time."}]}"""
        )
        coEvery { loreEntryRepository.upsert(any()) } returns Unit
        coJustRun { indexMemoryFragmentUseCase(any(), any(), any(), any()) }

        useCase(CHAT_ID, listOf(message(1)))

        coVerify {
            loreEntryRepository.upsert(
                withArg { entry ->
                    assertEquals("Early winter, three days before the wedding.", entry.occurredAt)
                    assertEquals("Enriched summary.", entry.summary)
                }
            )
        }
    }

    @Test
    fun `updates an existing entry by case-insensitive name match instead of duplicating`() = runTest {
        val existing = LoreEntryEntity(
            id = "entry-1",
            chatId = CHAT_ID,
            entryType = LoreEntryType.CHARACTER,
            name = "aria",
            summary = "old summary",
            content = "old content",
            isAutoGenerated = true,
            version = 2,
            createdAt = 10L,
            updatedAt = 10L
        )
        coEvery { loreEntryRepository.getByChat(CHAT_ID) } returns listOf(existing)
        coEvery { chatCompletionRepository.complete(any(), any(), any(), any(), any(), any(), any(), any(), any()) } returns completion(
            """{"entries": [{"name": "Aria", "entryType": "CHARACTER", "summary": "New info.", "content": "New content."}]}"""
        )
        coEvery { loreEntryRepository.upsert(any()) } returns Unit
        coJustRun { indexMemoryFragmentUseCase(any(), any(), any(), any()) }

        useCase(CHAT_ID, listOf(message(1)))

        coVerify {
            loreEntryRepository.upsert(
                withArg { entry ->
                    assertEquals("entry-1", entry.id)
                    assertEquals(3, entry.version)
                    assertEquals("New info.", entry.summary)
                    assertEquals(10L, entry.createdAt)
                }
            )
        }
    }

    @Test
    fun `falls back to CHARACTER for an unrecognized entry type`() = runTest {
        coEvery { loreEntryRepository.getByChat(CHAT_ID) } returns emptyList()
        coEvery { loreEntryRepository.findByChatAndNameOrAlias(CHAT_ID, any()) } returns null
        coEvery { chatCompletionRepository.complete(any(), any(), any(), any(), any(), any(), any(), any(), any()) } returns completion(
            """{"entries": [{"name": "Aria", "entryType": "NOT_A_REAL_TYPE", "summary": "s", "content": "c"}]}"""
        )
        coEvery { loreEntryRepository.upsert(any()) } returns Unit
        coJustRun { indexMemoryFragmentUseCase(any(), any(), any(), any()) }

        useCase(CHAT_ID, listOf(message(1)))

        coVerify { loreEntryRepository.upsert(withArg { entry -> assertEquals(LoreEntryType.CHARACTER, entry.entryType) }) }
    }

    @Test
    fun `skips entries with a blank name`() = runTest {
        coEvery { loreEntryRepository.getByChat(CHAT_ID) } returns emptyList()
        coEvery { chatCompletionRepository.complete(any(), any(), any(), any(), any(), any(), any(), any(), any()) } returns completion(
            """{"entries": [{"name": "", "entryType": "CHARACTER", "summary": "s", "content": "c"}]}"""
        )

        useCase(CHAT_ID, listOf(message(1)))

        coVerify(exactly = 0) { loreEntryRepository.upsert(any()) }
    }

    @Test
    fun `does nothing when the AI returns an empty entries array`() = runTest {
        coEvery { loreEntryRepository.getByChat(CHAT_ID) } returns emptyList()
        coEvery { chatCompletionRepository.complete(any(), any(), any(), any(), any(), any(), any(), any(), any()) } returns completion("""{"entries": []}""")

        useCase(CHAT_ID, listOf(message(1)))

        coVerify(exactly = 0) { loreEntryRepository.upsert(any()) }
    }

    @Test
    fun `never throws and upserts nothing when the completion call fails`() = runTest {
        coEvery { loreEntryRepository.getByChat(CHAT_ID) } returns emptyList()
        coEvery { chatCompletionRepository.complete(any(), any(), any(), any(), any(), any(), any(), any(), any()) } returns
            Result.failure(IllegalStateException("network down"))

        useCase(CHAT_ID, listOf(message(1)))

        coVerify(exactly = 0) { loreEntryRepository.upsert(any()) }
    }

    @Test
    fun `uses the model returned by the LLM resolver`() = runTest {
        coEvery { loreEntryRepository.getByChat(CHAT_ID) } returns emptyList()
        coEvery { chatCompletionRepository.complete(any(), any(), any(), any(), any(), any(), any(), any(), any()) } returns completion("""{"entries": []}""")

        useCase(CHAT_ID, listOf(message(1)))

        coVerify { llmModelResolver.resolve(any()) }
        coVerify { chatCompletionRepository.complete("gpt-4.1", any(), any(), any(), any(), any(), any(), any(), any()) }
    }

    @Test
    fun `persists a returned currentStoryTime onto the chat`() = runTest {
        coEvery { loreEntryRepository.getByChat(CHAT_ID) } returns emptyList()
        coEvery { chatCompletionRepository.complete(any(), any(), any(), any(), any(), any(), any(), any(), any()) } returns completion(
            """{"entries": [], "currentStoryTime": "Early winter, three days after the docks confrontation, mid-morning."}"""
        )
        coEvery { chatRepository.upsert(any()) } returns Unit

        useCase(CHAT_ID, listOf(message(1)))

        coVerify {
            chatRepository.upsert(
                withArg { chat ->
                    assertEquals("Early winter, three days after the docks confrontation, mid-morning.", chat.storyTimeAnchor)
                    assertTrue(chat.updatedAt > 0L)
                }
            )
        }
    }

    @Test
    fun `leaves the existing story time anchor untouched when the AI reports no time signal`() = runTest {
        coEvery { loreEntryRepository.getByChat(CHAT_ID) } returns emptyList()
        coEvery { chatCompletionRepository.complete(any(), any(), any(), any(), any(), any(), any(), any(), any()) } returns completion(
            """{"entries": [], "currentStoryTime": null}"""
        )

        useCase(CHAT_ID, listOf(message(1)))

        coVerify(exactly = 0) { chatRepository.upsert(any()) }
    }

    @Test
    fun `includes the existing story time anchor in the prompt sent to the classifier`() = runTest {
        coEvery { chatRepository.getById(CHAT_ID) } returns chatEntity(storyTimeAnchor = "Late summer, the evening after the festival.")
        coEvery { loreEntryRepository.getByChat(CHAT_ID) } returns emptyList()
        val messagesSlot = slot<List<ChatTurn>>()
        coEvery {
            chatCompletionRepository.complete(any(), any(), capture(messagesSlot), any(), any(), any(), any(), any(), any())
        } returns completion("""{"entries": []}""")

        useCase(CHAT_ID, listOf(message(1)))

        assertTrue(messagesSlot.captured.single().content.contains("Late summer, the evening after the festival."))
    }

    @Test
    fun `still upserts lore entries even when the story time upsert fails`() = runTest {
        coEvery { loreEntryRepository.getByChat(CHAT_ID) } returns emptyList()
        coEvery { loreEntryRepository.findByChatAndNameOrAlias(CHAT_ID, any()) } returns null
        coEvery { chatCompletionRepository.complete(any(), any(), any(), any(), any(), any(), any(), any(), any()) } returns completion(
            """{"entries": [{"name": "Aria", "entryType": "CHARACTER", "summary": "A mercenary.", "content": "Tall, silver hair."}], "currentStoryTime": "Late summer."}"""
        )
        coEvery { loreEntryRepository.upsert(any()) } returns Unit
        coJustRun { indexMemoryFragmentUseCase(any(), any(), any(), any()) }
        coEvery { chatRepository.upsert(any()) } throws IllegalStateException("db closed")

        useCase(CHAT_ID, listOf(message(1)))

        coVerify { loreEntryRepository.upsert(withArg { entry -> assertEquals("Aria", entry.name) }) }
    }

    @Test
    fun `records the aliases reported for a new entity`() = runTest {
        coEvery { loreEntryRepository.getByChat(CHAT_ID) } returns emptyList()
        coEvery { loreEntryRepository.findByChatAndNameOrAlias(CHAT_ID, any()) } returns null
        coEvery { chatCompletionRepository.complete(any(), any(), any(), any(), any(), any(), any(), any(), any()) } returns completion(
            """{"entries": [{"name": "Aria", "entryType": "CHARACTER", "summary": "A mercenary.", "content": "Tall.", "aliases": ["la mercenaire", "la Louve", "Aria"]}]}"""
        )
        coEvery { loreEntryRepository.upsert(any()) } returns Unit
        coJustRun { indexMemoryFragmentUseCase(any(), any(), any(), any()) }

        useCase(CHAT_ID, listOf(message(1)))

        coVerify {
            loreEntryRepository.upsert(withArg { entry ->
                // The entity's own name must never be echoed back into its alias list.
                assertEquals(listOf("la mercenaire", "la Louve"), entry.aliases)
            })
        }
    }

    @Test
    fun `merges into the existing sheet when the entity is only known by an alias`() = runTest {
        val existing = LoreEntryEntity(
            id = "entry-1",
            chatId = CHAT_ID,
            entryType = LoreEntryType.CHARACTER,
            name = "Aria",
            summary = "A mercenary.",
            content = "Tall, silver hair, carries a silver sword.",
            isAutoGenerated = true,
            aliases = listOf("la mercenaire"),
            version = 3,
            createdAt = 10L,
            updatedAt = 10L
        )
        coEvery { loreEntryRepository.getByChat(CHAT_ID) } returns listOf(existing)
        coEvery { chatCompletionRepository.complete(any(), any(), any(), any(), any(), any(), any(), any(), any()) } returns completion(
            """{"entries": [{"name": "la mercenaire", "entryType": "CHARACTER", "summary": "Une mercenaire.", "content": "Short."}]}"""
        )
        coEvery { loreEntryRepository.upsert(any()) } returns Unit
        coJustRun { indexMemoryFragmentUseCase(any(), any(), any(), any()) }

        useCase(CHAT_ID, listOf(message(1)))

        coVerify(exactly = 1) {
            loreEntryRepository.upsert(withArg { entry ->
                assertEquals("entry-1", entry.id)
                assertEquals("Aria", entry.name)
                assertEquals(4, entry.version)
                // A merge must never shrink a sheet: the longer content wins over the newer one.
                assertEquals("Tall, silver hair, carries a silver sword.", entry.content)
            })
        }
        coVerify(exactly = 0) { loreEntryRepository.findByChatAndNameOrAlias(any(), any()) }
    }

    @Test
    fun `follows an explicit sameAs link instead of creating a duplicate`() = runTest {
        val existing = LoreEntryEntity(
            id = "entry-1",
            chatId = CHAT_ID,
            entryType = LoreEntryType.CHARACTER,
            name = "Aria",
            summary = "A mercenary.",
            content = "Tall.",
            isAutoGenerated = true,
            version = 1,
            createdAt = 10L,
            updatedAt = 10L
        )
        coEvery { loreEntryRepository.getByChat(CHAT_ID) } returns listOf(existing)
        coEvery { chatCompletionRepository.complete(any(), any(), any(), any(), any(), any(), any(), any(), any()) } returns completion(
            """{"entries": [{"name": "la Louve", "entryType": "CHARACTER", "summary": "Une mercenaire.", "content": "Longer content here.", "sameAs": "Aria"}]}"""
        )
        coEvery { loreEntryRepository.upsert(any()) } returns Unit
        coJustRun { indexMemoryFragmentUseCase(any(), any(), any(), any()) }

        useCase(CHAT_ID, listOf(message(1)))

        coVerify(exactly = 1) {
            loreEntryRepository.upsert(withArg { entry ->
                assertEquals("entry-1", entry.id)
                assertEquals("Aria", entry.name)
                // The name it was referred to under becomes an alias, so the link sticks.
                assertTrue(entry.aliases.contains("la Louve"))
            })
        }
    }

    @Test
    fun `feeds known aliases back into the prompt roster`() = runTest {
        coEvery { chatRepository.getById(CHAT_ID) } returns chatEntity()
        coEvery { loreEntryRepository.getByChat(CHAT_ID) } returns listOf(
            LoreEntryEntity(
                id = "entry-1",
                chatId = CHAT_ID,
                entryType = LoreEntryType.CHARACTER,
                name = "Aria",
                summary = "A mercenary.",
                content = "Tall.",
                aliases = listOf("la mercenaire", "la Louve"),
                createdAt = 10L,
                updatedAt = 10L
            )
        )
        val messagesSlot = slot<List<ChatTurn>>()
        coEvery {
            chatCompletionRepository.complete(any(), any(), capture(messagesSlot), any(), any(), any(), any(), any(), any())
        } returns completion("""{"entries": []}""")

        useCase(CHAT_ID, listOf(message(1)))

        assertTrue(messagesSlot.captured.single().content.contains("Aria [aka: la mercenaire, la Louve]"))
    }
}
