package com.kitsune.core.data.local.entities

import androidx.room.Entity
import androidx.room.ForeignKey
import androidx.room.Index
import androidx.room.PrimaryKey

enum class LoreEntryType {
    CHARACTER,
    LOCATION,
    FACTION,
    EVENT,
    ITEM,

    /**
     * Une promesse narrative encore ouverte : question posée sans réponse, menace annoncée, objet
     * mystérieux, dette non réglée (2026-08-22).
     *
     * Volontairement un type de fiche de lore plutôt qu'une table dédiée : l'extraction, la fusion
     * par `sameAs`/`aliases`, le classement et la déduplication existent déjà et fonctionnent
     * exactement pareil ici. [LoreEntryEntity.anchorCreatedAt] fournit de surcroît la date de
     * plantation, donc l'ancienneté d'un fil se calcule **localement, sans appel LLM** — c'est ce
     * qui permet de signaler au modèle qu'un fil traîne et mérite d'être payé.
     */
    THREAD
}

/**
 * A "fiche de lore": a structured memory-tier-3 entity sheet (see FEATURES.md section 4) —
 * persistent characters, locations, factions, events and items extracted automatically from a
 * story so they survive far beyond the raw message window and the rolling summary (level 2).
 *
 * Scoped to a single [chatId] (a story) today, since universe creation (FEATURES.md section 6,
 * still 📋 planned) doesn't exist yet — [universeId] stays nullable for that future case, where a
 * lore entry could instead be shared across every chat of a whole universe. Exactly one of
 * [chatId]/[universeId] is expected to be non-null in practice; the DB itself doesn't enforce the
 * "exactly one" invariant (both FKs are independently nullable), callers must.
 */
@Entity(
    tableName = "lore_entries",
    foreignKeys = [
        ForeignKey(
            entity = UniverseEntity::class,
            parentColumns = ["id"],
            childColumns = ["universeId"],
            onDelete = ForeignKey.CASCADE
        ),
        ForeignKey(
            entity = ChatEntity::class,
            parentColumns = ["id"],
            childColumns = ["chatId"],
            onDelete = ForeignKey.CASCADE
        )
    ],
    indices = [Index("universeId"), Index("chatId"), Index("personaId")]
)
data class LoreEntryEntity(
    @PrimaryKey val id: String,
    val universeId: String? = null,
    val chatId: String? = null,
    /**
     * Lore that belongs to a **character** rather than to one story or one world (2026-08-25).
     *
     * Introduced for imported character cards: the `character_book` of a card is knowledge the
     * character carries wherever they are played, so it cannot be scoped to a chat that does not
     * exist yet, nor to a universe the importer never created. It gives lore the same three scopes
     * tone cards already have — chat, universe, character — and `BuildTurnMemoryUseCase` merges the
     * character's own sheets into every story that stars them.
     */
    val personaId: String? = null,
    val entryType: LoreEntryType,
    val name: String,
    val summary: String,
    val content: String,
    /** True for entries auto-generated by [com.kitsune.core.memory.lore.ExtractLoreEntriesUseCase] — includes mini-fiches for secondary/incidental NPCs, not just protagonists. */
    val isAutoGenerated: Boolean = false,
    /** Free-text point in the story's internal timeline when this happened — same free-prose
     *  philosophy as `ChatEntity.storyTimeAnchor`, only meaningful for [LoreEntryType.EVENT]
     *  entries. Set once when the entry is first extracted/created and never overwritten by later
     *  automatic re-extraction (when something happened is a fixed fact, unlike the entry's
     *  summary/content which keep being enriched) — only a manual user edit changes it afterward.
     *  Empty for non-EVENT entries and for events extracted before this field existed. */
    val occurredAt: String = "",
    /** `createdAt` of the last message in the batch this entry was first extracted from — the
     *  sortable counterpart to the free-text [occurredAt], which cannot be ordered.
     *
     *  Same "fixed fact" rule as [occurredAt]: written when the entry is created and never
     *  refreshed by a later re-extraction, since *when* an event happened doesn't change even as
     *  its summary/content keep being enriched. `0` for entries created before migration v27→v28.
     *  See `BuildStoryChronologyUseCase` for how the two fields are used together (this one
     *  orders, [occurredAt] labels). */
    val anchorCreatedAt: Long = 0L,
    /** Other names the story uses for this same entity — nicknames, titles, epithets, role
     *  descriptions ("la mercenaire"), alternate spellings.
     *
     *  Exists so re-extraction stops creating a second sheet whenever a character is referred to
     *  differently, which case-insensitive name matching alone could never catch. Populated by the
     *  extraction model, which is the only thing able to judge that "la mercenaire" and "Aria" are
     *  one person — that is a coreference judgment about the text, not a vector-distance property
     *  (see IDEAS.md 2026-08-15 for why embedding-similarity auto-merge was rejected).
     *
     *  Stored via the existing `Converters.fromTags`/`toTags` pair; no dedicated converter needed. */
    val aliases: List<String> = emptyList(),
    /**
     * Pour un [LoreEntryType.THREAD] : le fil a été payé, il cesse d'être injecté dans le prompt.
     * Toujours `false` pour les autres types — un lieu ou une faction ne se « résout » pas.
     *
     * Un fil résolu est conservé plutôt que supprimé : il reste une trace du récit, et le
     * réextraire à l'identique au tour suivant recréerait une entrée en double.
     */
    val resolved: Boolean = false,
    /**
     * Pour un [LoreEntryType.CHARACTER] : ce que ce personnage pense **actuellement** du personnage
     * de l'utilisateur — confiance, rancune, dette, attirance — et comment cela a évolué.
     *
     * Extrait par l'appel de lore déjà existant, au même titre que `summary`/`content` : aucun appel
     * supplémentaire. Vide pour les autres types et pour les fiches d'avant 2026-08-22.
     */
    val stance: String = "",
    val version: Int = 1,
    val createdAt: Long,
    val updatedAt: Long
)
